### ISSUE TITLE
Configuration for griffin

### ISSUE THREAD

**Issue by kasvith** [Mozilla-lk/griffin#1]
Griffin is supposed to be easily configurable, fast solution for monitoring external backend services.
It should be able to know the backends, their health check method(ping or GET), the interval of testing and notification methods

Since YAML is highly used in DevOps environments, it's better to stick with YAML syntax for the operation.

A sample config would be like

```yaml
services:
  - name: Foo Web Service
    host: foo.example.com
    health:
      - method: http
        endpoint: /status
        interval: 10s
      - method: ping
        interval: 5s
  - name: Bar Web Service
    host: bar.example.com
    health:
      - method: http
        endpoint: /statuz
        interval: 15s
      - method: ping
        interval: 10s
alerts:
  - type: Email
    from: griffin@foo.com
    to: webmaster@foo.com
  - type: Webhook
    url: https://mywebhook.com/abcd13345
```
