### ISSUE TITLE
Allow using params from environment variables

### ISSUE THREAD

**Issue by kasvith** [Mozilla-lk/griffin#15]
```yaml
# Sample griffin file

services:
  - name: Foo Web Service
    host: $FOO_HOST
    health:
      - method: http
        endpoint: /status
        port: 4040
        interval: 1h
      - method: ping
  - name: Bar Web Service
    host: bar.example.com
    health:
      - method: http
        endpoint: /statuz
        interval: 15s
      - method: ping
        interval: 30ms
alerts:
  - type: Email
    from: griffin@foo.com
    to: webmaster@foo.com
  - type: Webhook
    url: $WEBHOOK_URL
```

Need to expand the environment variables
